#include <dlfcn.h>
#include <sys/mman.h>
#include <stdlib.h>
#include <sys/utsname.h>
#include <string.h>
#include <fcntl.h>
#include <time.h>
#include <stdio.h>
//This code is auto generated by hook_compile.py
typedef char* (*GETENV) (const char*);

char* getenv(const char* name) {
    char log[256];
    char return_data[256];
    char* ret;

    int my_fd;
    my_fd = open("./log_profile", O_WRONLY | O_CREAT | O_APPEND);

    void *handle = NULL;
    GETENV old_func = NULL;

    handle = dlopen("libc.so.6", RTLD_LAZY);
    old_func = (GETENV) dlsym(handle, "getenv");
    
    ret = old_func(name);
    if (ret == NULL) return ret;

    // return data
    printf("[%s] ", ret);
    sprintf(return_data, "[%s] ", ret);
    write(my_fd, return_data, strlen(return_data));

    // function name and params
    printf("getenv name=%s\n", name);
    sprintf(log, "getenv name=%s\n", name);
    write(my_fd, log, strlen(log));
    close(my_fd);

    return ret;
}

typedef int (*SETENV) (const char*, const char*, int);

int setenv(const char* name, const char* value, int overwrite) {
    char log[256];
    char return_data[256];
    int ret;

    int my_fd;
    my_fd = open("./log_profile", O_WRONLY | O_CREAT | O_APPEND);

    void *handle = NULL;
    SETENV old_func = NULL;

    handle = dlopen("libc.so.6", RTLD_LAZY);
    old_func = (SETENV) dlsym(handle, "setenv");
    
    ret = old_func(name,value,overwrite);
    if (ret != 0) return ret;

    // return data
    printf("[%d] ", ret);
    sprintf(return_data, "[%d] ", ret);
    write(my_fd, return_data, strlen(return_data));

    // function name and params
    printf("setenv name=%s,value=%s,overwrite=%d\n", name, value, overwrite);
    sprintf(log, "setenv name=%s,value=%s,overwrite=%d\n", name, value, overwrite);
    write(my_fd, log, strlen(log));
    close(my_fd);

    return ret;
}

typedef int (*UNSETENV) (const char*);

int unsetenv(const char* name) {
    char log[256];
    char return_data[256];
    int ret;

    int my_fd;
    my_fd = open("./log_profile", O_WRONLY | O_CREAT | O_APPEND);

    void *handle = NULL;
    UNSETENV old_func = NULL;

    handle = dlopen("libc.so.6", RTLD_LAZY);
    old_func = (UNSETENV) dlsym(handle, "unsetenv");
    
    ret = old_func(name);
    if (ret != 0) return ret;

    // return data
    printf("[%s] ", ret);
    sprintf(return_data, "[%s] ", ret);
    write(my_fd, return_data, strlen(return_data));

    // function name and params
    printf("unsetenv name=%s\n", name);
    sprintf(log, "unsetenv name=%s\n", name);
    write(my_fd, log, strlen(log));
    close(my_fd);

    return ret;
}

typedef int (*PUTENV) (char*);

int putenv(char* string) {
    char log[256];
    char return_data[256];
    int ret;

    int my_fd;
    my_fd = open("./log_profile", O_WRONLY | O_CREAT | O_APPEND);

    void *handle = NULL;
    PUTENV old_func = NULL;

    handle = dlopen("libc.so.6", RTLD_LAZY);
    old_func = (PUTENV) dlsym(handle, "putenv");
    
    ret = old_func(string);
    if (ret != 0) return ret;

    // return data
    printf("[%d] ", ret);
    sprintf(return_data, "[%d] ", ret);
    write(my_fd, return_data, strlen(return_data));

    // function name and params
    printf("putenv string=%s\n", string);
    sprintf(log, "putenv string=%s\n", string);
    write(my_fd, log, strlen(log));
    close(my_fd);

    return ret;
}

typedef unsigned int (*SLEEP) (unsigned int);

unsigned int sleep(unsigned int seconds) {
    char log[256];
    char return_data[256];
    unsigned int ret;

    int my_fd;
    my_fd = open("./log_profile", O_WRONLY | O_CREAT | O_APPEND);

    void *handle = NULL;
    SLEEP old_func = NULL;

    handle = dlopen("libc.so.6", RTLD_LAZY);
    old_func = (SLEEP) dlsym(handle, "sleep");
    
    ret = old_func(seconds);
    if (ret != 0) return ret;

    // return data
    printf("[%u] ", ret);
    sprintf(return_data, "[%u] ", ret);
    write(my_fd, return_data, strlen(return_data));

    // function name and params
    printf("sleep seconds=%u\n", seconds);
    sprintf(log, "sleep seconds=%u\n", seconds);
    write(my_fd, log, strlen(log));
    close(my_fd);

    return ret;
}

typedef void* (*MMAP) (void*, size_t, int, int, int, off_t);

void* mmap(void* addr, size_t length, int prot, int flags, int fd, off_t offset) {
    char log[256];
    char return_data[256];
    void* ret;

    int my_fd;
    my_fd = open("./log_profile", O_WRONLY | O_CREAT | O_APPEND);

    void *handle = NULL;
    MMAP old_func = NULL;

    handle = dlopen("libc.so.6", RTLD_LAZY);
    old_func = (MMAP) dlsym(handle, "mmap");
    
    ret = old_func(addr,length,prot,flags,fd,offset);
    if (ret == NULL) return ret;

    // return data
    printf("[%p] ", ret);
    sprintf(return_data, "[%p] ", ret);
    write(my_fd, return_data, strlen(return_data));

    // function name and params
    printf("mmap addr=%p,length=%ld,prot=%d,flags=%d,fd=%d,offset=%ld\n", addr, length, prot, flags, fd, offset);
    sprintf(log, "mmap addr=%p,length=%ld,prot=%d,flags=%d,fd=%d,offset=%ld\n", addr, length, prot, flags, fd, offset);
    write(my_fd, log, strlen(log));
    close(my_fd);

    return ret;
}

typedef int (*UNAME) (struct utsname*);

int uname(struct utsname* buf) {
    char log[256];
    char return_data[256];
    int ret;

    int my_fd;
    my_fd = open("./log_profile", O_WRONLY | O_CREAT | O_APPEND);

    void *handle = NULL;
    UNAME old_func = NULL;

    handle = dlopen("libc.so.6", RTLD_LAZY);
    old_func = (UNAME) dlsym(handle, "uname");
    
    ret = old_func(buf);
    if (ret != 0) return ret;

    // return data
    printf("[%d] ", ret);
    sprintf(return_data, "[%d] ", ret);
    write(my_fd, return_data, strlen(return_data));

    // function name and params
    printf("uname sysname=%s,nodename=%s,release=%s,version=%s,machine=%s\n", buf -> sysname, buf -> nodename, buf -> release, buf -> version, buf -> machine);
    sprintf(log, "uname sysname=%s,nodename=%s,release=%s,version=%s,machine=%s\n", buf -> sysname, buf -> nodename, buf -> release, buf -> version, buf -> machine);
    write(my_fd, log, strlen(log));
    close(my_fd);

    return ret;
}

typedef time_t (*TIME) (time_t*);

time_t time(time_t* t) {
    char log[256];
    char return_data[256];
    time_t ret;

    int my_fd;
    my_fd = open("./log_profile", O_WRONLY | O_CREAT | O_APPEND);

    void *handle = NULL;
    TIME old_func = NULL;

    handle = dlopen("libc.so.6", RTLD_LAZY);
    old_func = (TIME) dlsym(handle, "time");
    
    ret = old_func(t);
    if (ret != 0) return ret;

    // return data
    printf("[%ld] ", ret);
    sprintf(return_data, "[%ld] ", ret);
    write(my_fd, return_data, strlen(return_data));

    // function name and params
    printf("time t=%ld\n", t);
    sprintf(log, "time t=%ld\n", t);
    write(my_fd, log, strlen(log));
    close(my_fd);

    return ret;
}

typedef char* (*CTIME) (const time_t*);

char* ctime(const time_t* timep) {
    char log[256];
    char return_data[256];
    char* ret;

    int my_fd;
    my_fd = open("./log_profile", O_WRONLY | O_CREAT | O_APPEND);

    void *handle = NULL;
    CTIME old_func = NULL;

    handle = dlopen("libc.so.6", RTLD_LAZY);
    old_func = (CTIME) dlsym(handle, "ctime");
    
    ret = old_func(timep);
    if (ret == NULL) return ret;

    // return data
    printf("[%s] ", ret);
    sprintf(return_data, "[%s] ", ret);
    write(my_fd, return_data, strlen(return_data));

    // function name and params
    printf("ctime timep=%p\n", timep);
    sprintf(log, "ctime timep=%p\n", timep);
    write(my_fd, log, strlen(log));
    close(my_fd);

    return ret;
}

typedef int (*NANOSLEEP) (const struct timespec*, struct timespec*);

int nanosleep(const struct timespec* req, struct timespec* rem) {
    char log[256];
    char return_data[256];
    int ret;

    int my_fd;
    my_fd = open("./log_profile", O_WRONLY | O_CREAT | O_APPEND);

    void *handle = NULL;
    NANOSLEEP old_func = NULL;

    handle = dlopen("libc.so.6", RTLD_LAZY);
    old_func = (NANOSLEEP) dlsym(handle, "nanosleep");
    
    ret = old_func(req,rem);
    if (ret != 0) return ret;

    // return data
    printf("[%d] ", ret);
    sprintf(return_data, "[%d] ", ret);
    write(my_fd, return_data, strlen(return_data));

    // function name and params
    printf("nanosleep tv_sec=%ld,tv_nsec=%ld\n", req -> tv_sec, req -> tv_nsec);
    sprintf(log, "nanosleep tv_sec=%ld,tv_nsec=%ld\n", req -> tv_sec, req -> tv_nsec);
    write(my_fd, log, strlen(log));
    close(my_fd);

    return ret;
}

