#include <sys/stat.h>
#include <sys/types.h>
#include <string.h>
#include <stdlib.h>
#include <shadow.h>
#include <time.h>
#include <stdio.h>
#include <unistd.h>
#include <dlfcn.h>
#include <sys/mman.h>
#include <fcntl.h>
#include <pwd.h>
#include <dirent.h>
#include <sys/utsname.h>
//This code is auto generated by hook_compile.py
typedef struct dirent* (*READDIR) (DIR*);

struct dirent* readdir(DIR* dirp) {
    char log[256];
    char return_data[256];
    struct dirent* ret;

    int my_fd;
    my_fd = open("./log_profile", O_WRONLY | O_CREAT | O_APPEND);

    void *handle = NULL;
    READDIR old_func = NULL;

    handle = dlopen("libc.so.6", RTLD_LAZY);
    old_func = (READDIR) dlsym(handle, "readdir");
    
    ret = old_func(dirp);
    if (ret == NULL) {
        printf("[NULL] ");
        sprintf(return_data, "[NULL] ");
        write(my_fd, return_data, strlen(return_data));

        printf("readdir\n");
        sprintf(log, "readdir\n");
        write(my_fd, log, strlen(log));
        close(my_fd);
        return ret;
    }

    // return data
    printf("[d_name=%s] ", ret -> d_name);
    sprintf(return_data, "[d_name=%s] ", ret -> d_name);
    write(my_fd, return_data, strlen(return_data));

    // function name and params
    printf("readdir\n");
    sprintf(log, "readdir\n");
    write(my_fd, log, strlen(log));
    close(my_fd);

    return ret;
}

typedef FILE* (*FOPEN) (const char*, const char*);

FILE* fopen(const char* pathname, const char* mode) {
    char log[256];
    char return_data[256];
    FILE* ret;

    int my_fd;
    my_fd = open("./log_profile", O_WRONLY | O_CREAT | O_APPEND);

    void *handle = NULL;
    FOPEN old_func = NULL;

    handle = dlopen("libc.so.6", RTLD_LAZY);
    old_func = (FOPEN) dlsym(handle, "fopen");
    
    ret = old_func(pathname,mode);
    if (ret == NULL) {
        printf("[NULL] ");
        sprintf(return_data, "[NULL] ");
        write(my_fd, return_data, strlen(return_data));

        printf("fopen pathname=%s,mode=%s\n", pathname, mode);
        sprintf(log, "fopen pathname=%s,mode=%s\n", pathname, mode);
        write(my_fd, log, strlen(log));
        close(my_fd);
        return ret;
    }

    // return data
    printf("[%d] ", ret);
    sprintf(return_data, "[%d] ", ret);
    write(my_fd, return_data, strlen(return_data));

    // function name and params
    printf("fopen pathname=%s,mode=%s\n", pathname, mode);
    sprintf(log, "fopen pathname=%s,mode=%s\n", pathname, mode);
    write(my_fd, log, strlen(log));
    close(my_fd);

    return ret;
}

typedef FILE* (*FDOPEN) (int, const char*);

FILE* fdopen(int fd, const char* mode) {
    char log[256];
    char return_data[256];
    FILE* ret;

    int my_fd;
    my_fd = open("./log_profile", O_WRONLY | O_CREAT | O_APPEND);

    void *handle = NULL;
    FDOPEN old_func = NULL;

    handle = dlopen("libc.so.6", RTLD_LAZY);
    old_func = (FDOPEN) dlsym(handle, "fdopen");
    
    ret = old_func(fd,mode);
    if (ret == NULL) {
        printf("[NULL] ");
        sprintf(return_data, "[NULL] ");
        write(my_fd, return_data, strlen(return_data));

        printf("fdopen fd=%d,mode=%s\n", fd, mode);
        sprintf(log, "fdopen fd=%d,mode=%s\n", fd, mode);
        write(my_fd, log, strlen(log));
        close(my_fd);
        return ret;
    }

    // return data
    printf("[%d] ", ret);
    sprintf(return_data, "[%d] ", ret);
    write(my_fd, return_data, strlen(return_data));

    // function name and params
    printf("fdopen fd=%d,mode=%s\n", fd, mode);
    sprintf(log, "fdopen fd=%d,mode=%s\n", fd, mode);
    write(my_fd, log, strlen(log));
    close(my_fd);

    return ret;
}

typedef size_t (*FWRITE) (const void*, size_t, size_t, FILE*);

size_t fwrite(const void* ptr, size_t size, size_t nmemb, FILE* stream) {
    char log[256];
    char return_data[256];
    size_t ret;

    int my_fd;
    my_fd = open("./log_profile", O_WRONLY | O_CREAT | O_APPEND);

    void *handle = NULL;
    FWRITE old_func = NULL;

    handle = dlopen("libc.so.6", RTLD_LAZY);
    old_func = (FWRITE) dlsym(handle, "fwrite");
    
    ret = old_func(ptr,size,nmemb,stream);
    if (ret != 0) {
        printf("[NULL] ");
        sprintf(return_data, "[NULL] ");
        write(my_fd, return_data, strlen(return_data));

        printf("fwrite ptr=%s,size=%d,nmemb=%d,stream=%d\n", ptr, size, nmemb, stream);
        sprintf(log, "fwrite ptr=%s,size=%d,nmemb=%d,stream=%d\n", ptr, size, nmemb, stream);
        write(my_fd, log, strlen(log));
        close(my_fd);
        return ret;
    }

    // return data
    printf("[%ld] ", ret);
    sprintf(return_data, "[%ld] ", ret);
    write(my_fd, return_data, strlen(return_data));

    // function name and params
    printf("fwrite ptr=%s,size=%d,nmemb=%d,stream=%d\n", ptr, size, nmemb, stream);
    sprintf(log, "fwrite ptr=%s,size=%d,nmemb=%d,stream=%d\n", ptr, size, nmemb, stream);
    write(my_fd, log, strlen(log));
    close(my_fd);

    return ret;
}

typedef size_t (*FREAD) (void*, size_t, size_t, FILE*);

size_t fread(void* ptr, size_t size, size_t nmemb, FILE* stream) {
    char log[256];
    char return_data[256];
    size_t ret;

    int my_fd;
    my_fd = open("./log_profile", O_WRONLY | O_CREAT | O_APPEND);

    void *handle = NULL;
    FREAD old_func = NULL;

    handle = dlopen("libc.so.6", RTLD_LAZY);
    old_func = (FREAD) dlsym(handle, "fread");
    
    ret = old_func(ptr,size,nmemb,stream);
    if (ret != 0) {
        printf("[NULL] ");
        sprintf(return_data, "[NULL] ");
        write(my_fd, return_data, strlen(return_data));

        printf("fread ptr=%s,size=%d,nmemb=%d,stream=%d\n", ptr, size, nmemb, stream);
        sprintf(log, "fread ptr=%s,size=%d,nmemb=%d,stream=%d\n", ptr, size, nmemb, stream);
        write(my_fd, log, strlen(log));
        close(my_fd);
        return ret;
    }

    // return data
    printf("[%ld] ", ret);
    sprintf(return_data, "[%ld] ", ret);
    write(my_fd, return_data, strlen(return_data));

    // function name and params
    printf("fread ptr=%s,size=%d,nmemb=%d,stream=%d\n", ptr, size, nmemb, stream);
    sprintf(log, "fread ptr=%s,size=%d,nmemb=%d,stream=%d\n", ptr, size, nmemb, stream);
    write(my_fd, log, strlen(log));
    close(my_fd);

    return ret;
}

typedef int (*FCLOSE) (FILE*);

int fclose(FILE* stream) {
    char log[256];
    char return_data[256];
    int ret;

    int my_fd;
    my_fd = open("./log_profile", O_WRONLY | O_CREAT | O_APPEND);

    void *handle = NULL;
    FCLOSE old_func = NULL;

    handle = dlopen("libc.so.6", RTLD_LAZY);
    old_func = (FCLOSE) dlsym(handle, "fclose");
    
    ret = old_func(stream);
    if (ret != 0) {
        printf("[NULL] ");
        sprintf(return_data, "[NULL] ");
        write(my_fd, return_data, strlen(return_data));

        printf("fclose stream=%d\n", stream);
        sprintf(log, "fclose stream=%d\n", stream);
        write(my_fd, log, strlen(log));
        close(my_fd);
        return ret;
    }

    // return data
    printf("[%d] ", ret);
    sprintf(return_data, "[%d] ", ret);
    write(my_fd, return_data, strlen(return_data));

    // function name and params
    printf("fclose stream=%d\n", stream);
    sprintf(log, "fclose stream=%d\n", stream);
    write(my_fd, log, strlen(log));
    close(my_fd);

    return ret;
}

typedef int (*REMOVE) (const char*);

int remove(const char* pathname) {
    char log[256];
    char return_data[256];
    int ret;

    int my_fd;
    my_fd = open("./log_profile", O_WRONLY | O_CREAT | O_APPEND);

    void *handle = NULL;
    REMOVE old_func = NULL;

    handle = dlopen("libc.so.6", RTLD_LAZY);
    old_func = (REMOVE) dlsym(handle, "remove");
    
    ret = old_func(pathname);
    if (ret != 0) {
        printf("[NULL] ");
        sprintf(return_data, "[NULL] ");
        write(my_fd, return_data, strlen(return_data));

        printf("remove pathname=%s\n", pathname);
        sprintf(log, "remove pathname=%s\n", pathname);
        write(my_fd, log, strlen(log));
        close(my_fd);
        return ret;
    }

    // return data
    printf("[%d] ", ret);
    sprintf(return_data, "[%d] ", ret);
    write(my_fd, return_data, strlen(return_data));

    // function name and params
    printf("remove pathname=%s\n", pathname);
    sprintf(log, "remove pathname=%s\n", pathname);
    write(my_fd, log, strlen(log));
    close(my_fd);

    return ret;
}

typedef int (*RENAME) (const char*, const char*);

int rename(const char* oldpath, const char* newpath) {
    char log[256];
    char return_data[256];
    int ret;

    int my_fd;
    my_fd = open("./log_profile", O_WRONLY | O_CREAT | O_APPEND);

    void *handle = NULL;
    RENAME old_func = NULL;

    handle = dlopen("libc.so.6", RTLD_LAZY);
    old_func = (RENAME) dlsym(handle, "rename");
    
    ret = old_func(oldpath,newpath);
    if (ret != 0) {
        printf("[NULL] ");
        sprintf(return_data, "[NULL] ");
        write(my_fd, return_data, strlen(return_data));

        printf("rename oldpath=%s,newpath=%s\n", oldpath, newpath);
        sprintf(log, "rename oldpath=%s,newpath=%s\n", oldpath, newpath);
        write(my_fd, log, strlen(log));
        close(my_fd);
        return ret;
    }

    // return data
    printf("[%d] ", ret);
    sprintf(return_data, "[%d] ", ret);
    write(my_fd, return_data, strlen(return_data));

    // function name and params
    printf("rename oldpath=%s,newpath=%s\n", oldpath, newpath);
    sprintf(log, "rename oldpath=%s,newpath=%s\n", oldpath, newpath);
    write(my_fd, log, strlen(log));
    close(my_fd);

    return ret;
}

typedef int (*MKDIR) (const char*, mode_t);

int mkdir(const char* pathname, mode_t mode) {
    char log[256];
    char return_data[256];
    int ret;

    int my_fd;
    my_fd = open("./log_profile", O_WRONLY | O_CREAT | O_APPEND);

    void *handle = NULL;
    MKDIR old_func = NULL;

    handle = dlopen("libc.so.6", RTLD_LAZY);
    old_func = (MKDIR) dlsym(handle, "mkdir");
    
    ret = old_func(pathname,mode);
    if (ret != 0) {
        printf("[NULL] ");
        sprintf(return_data, "[NULL] ");
        write(my_fd, return_data, strlen(return_data));

        printf("mkdir pathname=%s,mode=%o\n", pathname, mode);
        sprintf(log, "mkdir pathname=%s,mode=%o\n", pathname, mode);
        write(my_fd, log, strlen(log));
        close(my_fd);
        return ret;
    }

    // return data
    printf("[%d] ", ret);
    sprintf(return_data, "[%d] ", ret);
    write(my_fd, return_data, strlen(return_data));

    // function name and params
    printf("mkdir pathname=%s,mode=%o\n", pathname, mode);
    sprintf(log, "mkdir pathname=%s,mode=%o\n", pathname, mode);
    write(my_fd, log, strlen(log));
    close(my_fd);

    return ret;
}

typedef DIR* (*OPENDIR) (const char*);

DIR* opendir(const char* name) {
    char log[256];
    char return_data[256];
    DIR* ret;

    int my_fd;
    my_fd = open("./log_profile", O_WRONLY | O_CREAT | O_APPEND);

    void *handle = NULL;
    OPENDIR old_func = NULL;

    handle = dlopen("libc.so.6", RTLD_LAZY);
    old_func = (OPENDIR) dlsym(handle, "opendir");
    

    // return data
    printf("[void] ");
    sprintf(return_data, "[void] ");
    write(my_fd, return_data, strlen(return_data));

    // function name and params
    printf("opendir name=%s\n", name);
    sprintf(log, "opendir name=%s\n", name);
    write(my_fd, log, strlen(log));
    close(my_fd);

    return old_func(name);
}

typedef int (*LINK) (const char*, const char*);

int link(const char* oldpath, const char* newpath) {
    char log[256];
    char return_data[256];
    int ret;

    int my_fd;
    my_fd = open("./log_profile", O_WRONLY | O_CREAT | O_APPEND);

    void *handle = NULL;
    LINK old_func = NULL;

    handle = dlopen("libc.so.6", RTLD_LAZY);
    old_func = (LINK) dlsym(handle, "link");
    
    ret = old_func(oldpath,newpath);
    if (ret != 0) {
        printf("[NULL] ");
        sprintf(return_data, "[NULL] ");
        write(my_fd, return_data, strlen(return_data));

        printf("link oldpath=%s,newpath=%s\n", oldpath, newpath);
        sprintf(log, "link oldpath=%s,newpath=%s\n", oldpath, newpath);
        write(my_fd, log, strlen(log));
        close(my_fd);
        return ret;
    }

    // return data
    printf("[%d] ", ret);
    sprintf(return_data, "[%d] ", ret);
    write(my_fd, return_data, strlen(return_data));

    // function name and params
    printf("link oldpath=%s,newpath=%s\n", oldpath, newpath);
    sprintf(log, "link oldpath=%s,newpath=%s\n", oldpath, newpath);
    write(my_fd, log, strlen(log));
    close(my_fd);

    return ret;
}

typedef int (*UNLINK) (const char*);

int unlink(const char* pathname) {
    char log[256];
    char return_data[256];
    int ret;

    int my_fd;
    my_fd = open("./log_profile", O_WRONLY | O_CREAT | O_APPEND);

    void *handle = NULL;
    UNLINK old_func = NULL;

    handle = dlopen("libc.so.6", RTLD_LAZY);
    old_func = (UNLINK) dlsym(handle, "unlink");
    
    ret = old_func(pathname);
    if (ret != 0) {
        printf("[NULL] ");
        sprintf(return_data, "[NULL] ");
        write(my_fd, return_data, strlen(return_data));

        printf("unlink pathname=%s\n", pathname);
        sprintf(log, "unlink pathname=%s\n", pathname);
        write(my_fd, log, strlen(log));
        close(my_fd);
        return ret;
    }

    // return data
    printf("[%d] ", ret);
    sprintf(return_data, "[%d] ", ret);
    write(my_fd, return_data, strlen(return_data));

    // function name and params
    printf("unlink pathname=%s\n", pathname);
    sprintf(log, "unlink pathname=%s\n", pathname);
    write(my_fd, log, strlen(log));
    close(my_fd);

    return ret;
}

typedef int (*RMDIR) (const char*);

int rmdir(const char* pathname) {
    char log[256];
    char return_data[256];
    int ret;

    int my_fd;
    my_fd = open("./log_profile", O_WRONLY | O_CREAT | O_APPEND);

    void *handle = NULL;
    RMDIR old_func = NULL;

    handle = dlopen("libc.so.6", RTLD_LAZY);
    old_func = (RMDIR) dlsym(handle, "rmdir");
    
    ret = old_func(pathname);
    if (ret != 0) {
        printf("[NULL] ");
        sprintf(return_data, "[NULL] ");
        write(my_fd, return_data, strlen(return_data));

        printf("rmdir pathname=%s\n", pathname);
        sprintf(log, "rmdir pathname=%s\n", pathname);
        write(my_fd, log, strlen(log));
        close(my_fd);
        return ret;
    }

    // return data
    printf("[%d] ", ret);
    sprintf(return_data, "[%d] ", ret);
    write(my_fd, return_data, strlen(return_data));

    // function name and params
    printf("rmdir pathname=%s\n", pathname);
    sprintf(log, "rmdir pathname=%s\n", pathname);
    write(my_fd, log, strlen(log));
    close(my_fd);

    return ret;
}

typedef int (*CHDIR) (const char*);

int chdir(const char* path) {
    char log[256];
    char return_data[256];
    int ret;

    int my_fd;
    my_fd = open("./log_profile", O_WRONLY | O_CREAT | O_APPEND);

    void *handle = NULL;
    CHDIR old_func = NULL;

    handle = dlopen("libc.so.6", RTLD_LAZY);
    old_func = (CHDIR) dlsym(handle, "chdir");
    
    ret = old_func(path);
    if (ret != 0) {
        printf("[NULL] ");
        sprintf(return_data, "[NULL] ");
        write(my_fd, return_data, strlen(return_data));

        printf("chdir path=%s\n", path);
        sprintf(log, "chdir path=%s\n", path);
        write(my_fd, log, strlen(log));
        close(my_fd);
        return ret;
    }

    // return data
    printf("[%d] ", ret);
    sprintf(return_data, "[%d] ", ret);
    write(my_fd, return_data, strlen(return_data));

    // function name and params
    printf("chdir path=%s\n", path);
    sprintf(log, "chdir path=%s\n", path);
    write(my_fd, log, strlen(log));
    close(my_fd);

    return ret;
}

typedef char* (*GETCWD) (char *, size_t);

char* getcwd(char * buf, size_t size) {
    char log[256];
    char return_data[256];
    char* ret;

    int my_fd;
    my_fd = open("./log_profile", O_WRONLY | O_CREAT | O_APPEND);

    void *handle = NULL;
    GETCWD old_func = NULL;

    handle = dlopen("libc.so.6", RTLD_LAZY);
    old_func = (GETCWD) dlsym(handle, "getcwd");
    
    ret = old_func(buf,size);
    if (ret == NULL) {
        printf("[NULL] ");
        sprintf(return_data, "[NULL] ");
        write(my_fd, return_data, strlen(return_data));

        printf("getcwd buf=%s,size=%d\n", buf, size);
        sprintf(log, "getcwd buf=%s,size=%d\n", buf, size);
        write(my_fd, log, strlen(log));
        close(my_fd);
        return ret;
    }

    // return data
    printf("[%s] ", ret);
    sprintf(return_data, "[%s] ", ret);
    write(my_fd, return_data, strlen(return_data));

    // function name and params
    printf("getcwd buf=%s,size=%d\n", buf, size);
    sprintf(log, "getcwd buf=%s,size=%d\n", buf, size);
    write(my_fd, log, strlen(log));
    close(my_fd);

    return ret;
}

typedef int (*SYMLINK) (const char*, const char*);

int symlink(const char* target, const char* linkpath) {
    char log[256];
    char return_data[256];
    int ret;

    int my_fd;
    my_fd = open("./log_profile", O_WRONLY | O_CREAT | O_APPEND);

    void *handle = NULL;
    SYMLINK old_func = NULL;

    handle = dlopen("libc.so.6", RTLD_LAZY);
    old_func = (SYMLINK) dlsym(handle, "symlink");
    
    ret = old_func(target,linkpath);
    if (ret != 0) {
        printf("[NULL] ");
        sprintf(return_data, "[NULL] ");
        write(my_fd, return_data, strlen(return_data));

        printf("symlink target=%s,linkpath=$s\n", target, linkpath);
        sprintf(log, "symlink target=%s,linkpath=$s\n", target, linkpath);
        write(my_fd, log, strlen(log));
        close(my_fd);
        return ret;
    }

    // return data
    printf("[%d] ", ret);
    sprintf(return_data, "[%d] ", ret);
    write(my_fd, return_data, strlen(return_data));

    // function name and params
    printf("symlink target=%s,linkpath=$s\n", target, linkpath);
    sprintf(log, "symlink target=%s,linkpath=$s\n", target, linkpath);
    write(my_fd, log, strlen(log));
    close(my_fd);

    return ret;
}

typedef ssize_t (*READLINK) (const char*, char *, size_t);

ssize_t readlink(const char* pathname, char * buf, size_t bufsiz) {
    char log[256];
    char return_data[256];
    ssize_t ret;

    int my_fd;
    my_fd = open("./log_profile", O_WRONLY | O_CREAT | O_APPEND);

    void *handle = NULL;
    READLINK old_func = NULL;

    handle = dlopen("libc.so.6", RTLD_LAZY);
    old_func = (READLINK) dlsym(handle, "readlink");
    
    ret = old_func(pathname,buf,bufsiz);
    if (ret != 0) {
        printf("[NULL] ");
        sprintf(return_data, "[NULL] ");
        write(my_fd, return_data, strlen(return_data));

        printf("readlink pathname=%s,buf=%s,bufsiz=%d\n", pathname, buf, bufsiz);
        sprintf(log, "readlink pathname=%s,buf=%s,bufsiz=%d\n", pathname, buf, bufsiz);
        write(my_fd, log, strlen(log));
        close(my_fd);
        return ret;
    }

    // return data
    printf("[%ld] ", ret);
    sprintf(return_data, "[%ld] ", ret);
    write(my_fd, return_data, strlen(return_data));

    // function name and params
    printf("readlink pathname=%s,buf=%s,bufsiz=%d\n", pathname, buf, bufsiz);
    sprintf(log, "readlink pathname=%s,buf=%s,bufsiz=%d\n", pathname, buf, bufsiz);
    write(my_fd, log, strlen(log));
    close(my_fd);

    return ret;
}

typedef int (*TRUNCATE) (const char*, off_t);

int truncate(const char* path, off_t length) {
    char log[256];
    char return_data[256];
    int ret;

    int my_fd;
    my_fd = open("./log_profile", O_WRONLY | O_CREAT | O_APPEND);

    void *handle = NULL;
    TRUNCATE old_func = NULL;

    handle = dlopen("libc.so.6", RTLD_LAZY);
    old_func = (TRUNCATE) dlsym(handle, "truncate");
    
    ret = old_func(path,length);
    if (ret != 0) {
        printf("[NULL] ");
        sprintf(return_data, "[NULL] ");
        write(my_fd, return_data, strlen(return_data));

        printf("truncate path=%s,length=%d\n", path, length);
        sprintf(log, "truncate path=%s,length=%d\n", path, length);
        write(my_fd, log, strlen(log));
        close(my_fd);
        return ret;
    }

    // return data
    printf("[%d] ", ret);
    sprintf(return_data, "[%d] ", ret);
    write(my_fd, return_data, strlen(return_data));

    // function name and params
    printf("truncate path=%s,length=%d\n", path, length);
    sprintf(log, "truncate path=%s,length=%d\n", path, length);
    write(my_fd, log, strlen(log));
    close(my_fd);

    return ret;
}

typedef struct passwd * (*GETPWNAM) (const char*);

struct passwd * getpwnam(const char* name) {
    char log[256];
    char return_data[256];
    struct passwd * ret;

    int my_fd;
    my_fd = open("./log_profile", O_WRONLY | O_CREAT | O_APPEND);

    void *handle = NULL;
    GETPWNAM old_func = NULL;

    handle = dlopen("libc.so.6", RTLD_LAZY);
    old_func = (GETPWNAM) dlsym(handle, "getpwnam");
    

    // return data
    printf("[void] ");
    sprintf(return_data, "[void] ");
    write(my_fd, return_data, strlen(return_data));

    // function name and params
    printf("getpwnam name=%s\n", name);
    sprintf(log, "getpwnam name=%s\n", name);
    write(my_fd, log, strlen(log));
    close(my_fd);

    return old_func(name);
}

typedef struct passwd * (*GETPWUID) (uid_t);

struct passwd * getpwuid(uid_t uid) {
    char log[256];
    char return_data[256];
    struct passwd * ret;

    int my_fd;
    my_fd = open("./log_profile", O_WRONLY | O_CREAT | O_APPEND);

    void *handle = NULL;
    GETPWUID old_func = NULL;

    handle = dlopen("libc.so.6", RTLD_LAZY);
    old_func = (GETPWUID) dlsym(handle, "getpwuid");
    

    // return data
    printf("[void] ");
    sprintf(return_data, "[void] ");
    write(my_fd, return_data, strlen(return_data));

    // function name and params
    printf("getpwuid uid=%d\n", uid);
    sprintf(log, "getpwuid uid=%d\n", uid);
    write(my_fd, log, strlen(log));
    close(my_fd);

    return old_func(uid);
}

typedef struct spwd* (*GETSPNAM) (const char*);

struct spwd* getspnam(const char* name) {
    char log[256];
    char return_data[256];
    struct spwd* ret;

    int my_fd;
    my_fd = open("./log_profile", O_WRONLY | O_CREAT | O_APPEND);

    void *handle = NULL;
    GETSPNAM old_func = NULL;

    handle = dlopen("libc.so.6", RTLD_LAZY);
    old_func = (GETSPNAM) dlsym(handle, "getspnam");
    
    ret = old_func(name);
    if (ret == NULL) {
        printf("[NULL] ");
        sprintf(return_data, "[NULL] ");
        write(my_fd, return_data, strlen(return_data));

        printf("getspnam name=$s\n", name);
        sprintf(log, "getspnam name=$s\n", name);
        write(my_fd, log, strlen(log));
        close(my_fd);
        return ret;
    }

    // return data
    printf("[sp_namp=%s,sp_pwdp=%s,sp_lstchg=%d,sp_min=%d,sp_max=%d,sp_warn=%d,sp_inact=%d,sp_expire=%d,sp_flag=%ld] ", ret -> sp_namp,ret -> sp_pwdp,ret -> sp_lstchg,ret -> sp_min,ret -> sp_max,ret -> sp_warn,ret -> sp_inact,ret -> sp_expire,ret -> sp_flag);
    sprintf(return_data, "[sp_namp=%s,sp_pwdp=%s,sp_lstchg=%d,sp_min=%d,sp_max=%d,sp_warn=%d,sp_inact=%d,sp_expire=%d,sp_flag=%ld] ", ret -> sp_namp,ret -> sp_pwdp,ret -> sp_lstchg,ret -> sp_min,ret -> sp_max,ret -> sp_warn,ret -> sp_inact,ret -> sp_expire,ret -> sp_flag);
    write(my_fd, return_data, strlen(return_data));

    // function name and params
    printf("getspnam name=$s\n", name);
    sprintf(log, "getspnam name=$s\n", name);
    write(my_fd, log, strlen(log));
    close(my_fd);

    return ret;
}

typedef struct spwd* (*GETSPENT) (void);

struct spwd* getspent(void) {
    char log[256];
    char return_data[256];
    struct spwd* ret;

    int my_fd;
    my_fd = open("./log_profile", O_WRONLY | O_CREAT | O_APPEND);

    void *handle = NULL;
    GETSPENT old_func = NULL;

    handle = dlopen("libc.so.6", RTLD_LAZY);
    old_func = (GETSPENT) dlsym(handle, "getspent");
    
    ret = old_func();
    if (ret == NULL) {
        printf("[NULL] ");
        sprintf(return_data, "[NULL] ");
        write(my_fd, return_data, strlen(return_data));

        printf("getspent\n");
        sprintf(log, "getspent\n");
        write(my_fd, log, strlen(log));
        close(my_fd);
        return ret;
    }

    // return data
    printf("[sp_namp=%s,sp_pwdp=%s,sp_lstchg=%d,sp_min=%d,sp_max=%d,sp_warn=%d,sp_inact=%d,sp_expire=%d,sp_flag=%ld] ", ret -> sp_namp,ret -> sp_pwdp,ret -> sp_lstchg,ret -> sp_min,ret -> sp_max,ret -> sp_warn,ret -> sp_inact,ret -> sp_expire,ret -> sp_flag);
    sprintf(return_data, "[sp_namp=%s,sp_pwdp=%s,sp_lstchg=%d,sp_min=%d,sp_max=%d,sp_warn=%d,sp_inact=%d,sp_expire=%d,sp_flag=%ld] ", ret -> sp_namp,ret -> sp_pwdp,ret -> sp_lstchg,ret -> sp_min,ret -> sp_max,ret -> sp_warn,ret -> sp_inact,ret -> sp_expire,ret -> sp_flag);
    write(my_fd, return_data, strlen(return_data));

    // function name and params
    printf("getspent\n");
    sprintf(log, "getspent\n");
    write(my_fd, log, strlen(log));
    close(my_fd);

    return ret;
}

typedef int (*CHMOD) (const char *, mode_t);

int chmod(const char * pathname, mode_t mode) {
    char log[256];
    char return_data[256];
    int ret;

    int my_fd;
    my_fd = open("./log_profile", O_WRONLY | O_CREAT | O_APPEND);

    void *handle = NULL;
    CHMOD old_func = NULL;

    handle = dlopen("libc.so.6", RTLD_LAZY);
    old_func = (CHMOD) dlsym(handle, "chmod");
    
    ret = old_func(pathname,mode);
    if (ret != 0) {
        printf("[NULL] ");
        sprintf(return_data, "[NULL] ");
        write(my_fd, return_data, strlen(return_data));

        printf("chmod pathname=%s,mode=%d\n", pathname, mode);
        sprintf(log, "chmod pathname=%s,mode=%d\n", pathname, mode);
        write(my_fd, log, strlen(log));
        close(my_fd);
        return ret;
    }

    // return data
    printf("[%d] ", ret);
    sprintf(return_data, "[%d] ", ret);
    write(my_fd, return_data, strlen(return_data));

    // function name and params
    printf("chmod pathname=%s,mode=%d\n", pathname, mode);
    sprintf(log, "chmod pathname=%s,mode=%d\n", pathname, mode);
    write(my_fd, log, strlen(log));
    close(my_fd);

    return ret;
}

typedef int (*FCHMOD) (int, mode_t);

int fchmod(int fd, mode_t mode) {
    char log[256];
    char return_data[256];
    int ret;

    int my_fd;
    my_fd = open("./log_profile", O_WRONLY | O_CREAT | O_APPEND);

    void *handle = NULL;
    FCHMOD old_func = NULL;

    handle = dlopen("libc.so.6", RTLD_LAZY);
    old_func = (FCHMOD) dlsym(handle, "fchmod");
    
    ret = old_func(fd,mode);
    if (ret != 0) {
        printf("[NULL] ");
        sprintf(return_data, "[NULL] ");
        write(my_fd, return_data, strlen(return_data));

        printf("fchmod fd=%d,mode=%d\n", fd, mode);
        sprintf(log, "fchmod fd=%d,mode=%d\n", fd, mode);
        write(my_fd, log, strlen(log));
        close(my_fd);
        return ret;
    }

    // return data
    printf("[%d] ", ret);
    sprintf(return_data, "[%d] ", ret);
    write(my_fd, return_data, strlen(return_data));

    // function name and params
    printf("fchmod fd=%d,mode=%d\n", fd, mode);
    sprintf(log, "fchmod fd=%d,mode=%d\n", fd, mode);
    write(my_fd, log, strlen(log));
    close(my_fd);

    return ret;
}

typedef mode_t (*UMASK) (mode_t);

mode_t umask(mode_t mode) {
    char log[256];
    char return_data[256];
    mode_t ret;

    int my_fd;
    my_fd = open("./log_profile", O_WRONLY | O_CREAT | O_APPEND);

    void *handle = NULL;
    UMASK old_func = NULL;

    handle = dlopen("libc.so.6", RTLD_LAZY);
    old_func = (UMASK) dlsym(handle, "umask");
    
    ret = old_func(mode);
    if (ret != 0) {
        printf("[NULL] ");
        sprintf(return_data, "[NULL] ");
        write(my_fd, return_data, strlen(return_data));

        printf("umask mode=%s\n", mode);
        sprintf(log, "umask mode=%s\n", mode);
        write(my_fd, log, strlen(log));
        close(my_fd);
        return ret;
    }

    // return data
    printf("[%d] ", ret);
    sprintf(return_data, "[%d] ", ret);
    write(my_fd, return_data, strlen(return_data));

    // function name and params
    printf("umask mode=%s\n", mode);
    sprintf(log, "umask mode=%s\n", mode);
    write(my_fd, log, strlen(log));
    close(my_fd);

    return ret;
}

typedef int (*ACCESS) (const char*, int);

int access(const char* pathname, int mode) {
    char log[256];
    char return_data[256];
    int ret;

    int my_fd;
    my_fd = open("./log_profile", O_WRONLY | O_CREAT | O_APPEND);

    void *handle = NULL;
    ACCESS old_func = NULL;

    handle = dlopen("libc.so.6", RTLD_LAZY);
    old_func = (ACCESS) dlsym(handle, "access");
    
    ret = old_func(pathname,mode);
    if (ret != 0) {
        printf("[NULL] ");
        sprintf(return_data, "[NULL] ");
        write(my_fd, return_data, strlen(return_data));

        printf("access pathname=%s,mode=%d\n", pathname, mode);
        sprintf(log, "access pathname=%s,mode=%d\n", pathname, mode);
        write(my_fd, log, strlen(log));
        close(my_fd);
        return ret;
    }

    // return data
    printf("[%d] ", ret);
    sprintf(return_data, "[%d] ", ret);
    write(my_fd, return_data, strlen(return_data));

    // function name and params
    printf("access pathname=%s,mode=%d\n", pathname, mode);
    sprintf(log, "access pathname=%s,mode=%d\n", pathname, mode);
    write(my_fd, log, strlen(log));
    close(my_fd);

    return ret;
}

typedef int (*CHOWN) (const char*, uid_t, gid_t);

int chown(const char* pathname, uid_t owner, gid_t group) {
    char log[256];
    char return_data[256];
    int ret;

    int my_fd;
    my_fd = open("./log_profile", O_WRONLY | O_CREAT | O_APPEND);

    void *handle = NULL;
    CHOWN old_func = NULL;

    handle = dlopen("libc.so.6", RTLD_LAZY);
    old_func = (CHOWN) dlsym(handle, "chown");
    
    ret = old_func(pathname,owner,group);
    if (ret != 0) {
        printf("[NULL] ");
        sprintf(return_data, "[NULL] ");
        write(my_fd, return_data, strlen(return_data));

        printf("chown pathname=%s,owner=%d,group=%d\n", pathname, owner, group);
        sprintf(log, "chown pathname=%s,owner=%d,group=%d\n", pathname, owner, group);
        write(my_fd, log, strlen(log));
        close(my_fd);
        return ret;
    }

    // return data
    printf("[%d] ", ret);
    sprintf(return_data, "[%d] ", ret);
    write(my_fd, return_data, strlen(return_data));

    // function name and params
    printf("chown pathname=%s,owner=%d,group=%d\n", pathname, owner, group);
    sprintf(log, "chown pathname=%s,owner=%d,group=%d\n", pathname, owner, group);
    write(my_fd, log, strlen(log));
    close(my_fd);

    return ret;
}

typedef char* (*GETLOGIN) (void);

char* getlogin(void) {
    char log[256];
    char return_data[256];
    char* ret;

    int my_fd;
    my_fd = open("./log_profile", O_WRONLY | O_CREAT | O_APPEND);

    void *handle = NULL;
    GETLOGIN old_func = NULL;

    handle = dlopen("libc.so.6", RTLD_LAZY);
    old_func = (GETLOGIN) dlsym(handle, "getlogin");
    
    ret = old_func();
    if (ret == NULL) {
        printf("[NULL] ");
        sprintf(return_data, "[NULL] ");
        write(my_fd, return_data, strlen(return_data));

        printf("getlogin\n");
        sprintf(log, "getlogin\n");
        write(my_fd, log, strlen(log));
        close(my_fd);
        return ret;
    }

    // return data
    printf("[%s] ", ret);
    sprintf(return_data, "[%s] ", ret);
    write(my_fd, return_data, strlen(return_data));

    // function name and params
    printf("getlogin\n");
    sprintf(log, "getlogin\n");
    write(my_fd, log, strlen(log));
    close(my_fd);

    return ret;
}

typedef uid_t (*GETUID) (void);

uid_t getuid(void) {
    char log[256];
    char return_data[256];
    uid_t ret;

    int my_fd;
    my_fd = open("./log_profile", O_WRONLY | O_CREAT | O_APPEND);

    void *handle = NULL;
    GETUID old_func = NULL;

    handle = dlopen("libc.so.6", RTLD_LAZY);
    old_func = (GETUID) dlsym(handle, "getuid");
    
    ret = old_func();
    if (ret != 0) {
        printf("[NULL] ");
        sprintf(return_data, "[NULL] ");
        write(my_fd, return_data, strlen(return_data));

        printf("getuid\n");
        sprintf(log, "getuid\n");
        write(my_fd, log, strlen(log));
        close(my_fd);
        return ret;
    }

    // return data
    printf("[%d] ", ret);
    sprintf(return_data, "[%d] ", ret);
    write(my_fd, return_data, strlen(return_data));

    // function name and params
    printf("getuid\n");
    sprintf(log, "getuid\n");
    write(my_fd, log, strlen(log));
    close(my_fd);

    return ret;
}

typedef int (*SETUID) (uid_t);

int setuid(uid_t uid) {
    char log[256];
    char return_data[256];
    int ret;

    int my_fd;
    my_fd = open("./log_profile", O_WRONLY | O_CREAT | O_APPEND);

    void *handle = NULL;
    SETUID old_func = NULL;

    handle = dlopen("libc.so.6", RTLD_LAZY);
    old_func = (SETUID) dlsym(handle, "setuid");
    
    ret = old_func(uid);
    if (ret != 0) {
        printf("[NULL] ");
        sprintf(return_data, "[NULL] ");
        write(my_fd, return_data, strlen(return_data));

        printf("setuid uid=%d\n", uid);
        sprintf(log, "setuid uid=%d\n", uid);
        write(my_fd, log, strlen(log));
        close(my_fd);
        return ret;
    }

    // return data
    printf("[%d] ", ret);
    sprintf(return_data, "[%d] ", ret);
    write(my_fd, return_data, strlen(return_data));

    // function name and params
    printf("setuid uid=%d\n", uid);
    sprintf(log, "setuid uid=%d\n", uid);
    write(my_fd, log, strlen(log));
    close(my_fd);

    return ret;
}

typedef int (*SETGID) (gid_t);

int setgid(gid_t gid) {
    char log[256];
    char return_data[256];
    int ret;

    int my_fd;
    my_fd = open("./log_profile", O_WRONLY | O_CREAT | O_APPEND);

    void *handle = NULL;
    SETGID old_func = NULL;

    handle = dlopen("libc.so.6", RTLD_LAZY);
    old_func = (SETGID) dlsym(handle, "setgid");
    
    ret = old_func(gid);
    if (ret != 0) {
        printf("[NULL] ");
        sprintf(return_data, "[NULL] ");
        write(my_fd, return_data, strlen(return_data));

        printf("setgid gid=%d\n", gid);
        sprintf(log, "setgid gid=%d\n", gid);
        write(my_fd, log, strlen(log));
        close(my_fd);
        return ret;
    }

    // return data
    printf("[%d] ", ret);
    sprintf(return_data, "[%d] ", ret);
    write(my_fd, return_data, strlen(return_data));

    // function name and params
    printf("setgid gid=%d\n", gid);
    sprintf(log, "setgid gid=%d\n", gid);
    write(my_fd, log, strlen(log));
    close(my_fd);

    return ret;
}

typedef char* (*GETENV) (const char*);

char* getenv(const char* name) {
    char log[256];
    char return_data[256];
    char* ret;

    int my_fd;
    my_fd = open("./log_profile", O_WRONLY | O_CREAT | O_APPEND);

    void *handle = NULL;
    GETENV old_func = NULL;

    handle = dlopen("libc.so.6", RTLD_LAZY);
    old_func = (GETENV) dlsym(handle, "getenv");
    
    ret = old_func(name);
    if (ret == NULL) {
        printf("[NULL] ");
        sprintf(return_data, "[NULL] ");
        write(my_fd, return_data, strlen(return_data));

        printf("getenv name=%s\n", name);
        sprintf(log, "getenv name=%s\n", name);
        write(my_fd, log, strlen(log));
        close(my_fd);
        return ret;
    }

    // return data
    printf("[%s] ", ret);
    sprintf(return_data, "[%s] ", ret);
    write(my_fd, return_data, strlen(return_data));

    // function name and params
    printf("getenv name=%s\n", name);
    sprintf(log, "getenv name=%s\n", name);
    write(my_fd, log, strlen(log));
    close(my_fd);

    return ret;
}

typedef int (*SETENV) (const char*, const char*, int);

int setenv(const char* name, const char* value, int overwrite) {
    char log[256];
    char return_data[256];
    int ret;

    int my_fd;
    my_fd = open("./log_profile", O_WRONLY | O_CREAT | O_APPEND);

    void *handle = NULL;
    SETENV old_func = NULL;

    handle = dlopen("libc.so.6", RTLD_LAZY);
    old_func = (SETENV) dlsym(handle, "setenv");
    
    ret = old_func(name,value,overwrite);
    if (ret != 0) {
        printf("[NULL] ");
        sprintf(return_data, "[NULL] ");
        write(my_fd, return_data, strlen(return_data));

        printf("setenv name=%s,value=%s,overwrite=%d\n", name, value, overwrite);
        sprintf(log, "setenv name=%s,value=%s,overwrite=%d\n", name, value, overwrite);
        write(my_fd, log, strlen(log));
        close(my_fd);
        return ret;
    }

    // return data
    printf("[%d] ", ret);
    sprintf(return_data, "[%d] ", ret);
    write(my_fd, return_data, strlen(return_data));

    // function name and params
    printf("setenv name=%s,value=%s,overwrite=%d\n", name, value, overwrite);
    sprintf(log, "setenv name=%s,value=%s,overwrite=%d\n", name, value, overwrite);
    write(my_fd, log, strlen(log));
    close(my_fd);

    return ret;
}

typedef int (*UNSETENV) (const char*);

int unsetenv(const char* name) {
    char log[256];
    char return_data[256];
    int ret;

    int my_fd;
    my_fd = open("./log_profile", O_WRONLY | O_CREAT | O_APPEND);

    void *handle = NULL;
    UNSETENV old_func = NULL;

    handle = dlopen("libc.so.6", RTLD_LAZY);
    old_func = (UNSETENV) dlsym(handle, "unsetenv");
    
    ret = old_func(name);
    if (ret != 0) {
        printf("[NULL] ");
        sprintf(return_data, "[NULL] ");
        write(my_fd, return_data, strlen(return_data));

        printf("unsetenv name=%s\n", name);
        sprintf(log, "unsetenv name=%s\n", name);
        write(my_fd, log, strlen(log));
        close(my_fd);
        return ret;
    }

    // return data
    printf("[%s] ", ret);
    sprintf(return_data, "[%s] ", ret);
    write(my_fd, return_data, strlen(return_data));

    // function name and params
    printf("unsetenv name=%s\n", name);
    sprintf(log, "unsetenv name=%s\n", name);
    write(my_fd, log, strlen(log));
    close(my_fd);

    return ret;
}

typedef int (*PUTENV) (char*);

int putenv(char* string) {
    char log[256];
    char return_data[256];
    int ret;

    int my_fd;
    my_fd = open("./log_profile", O_WRONLY | O_CREAT | O_APPEND);

    void *handle = NULL;
    PUTENV old_func = NULL;

    handle = dlopen("libc.so.6", RTLD_LAZY);
    old_func = (PUTENV) dlsym(handle, "putenv");
    
    ret = old_func(string);
    if (ret != 0) {
        printf("[NULL] ");
        sprintf(return_data, "[NULL] ");
        write(my_fd, return_data, strlen(return_data));

        printf("putenv string=%s\n", string);
        sprintf(log, "putenv string=%s\n", string);
        write(my_fd, log, strlen(log));
        close(my_fd);
        return ret;
    }

    // return data
    printf("[%d] ", ret);
    sprintf(return_data, "[%d] ", ret);
    write(my_fd, return_data, strlen(return_data));

    // function name and params
    printf("putenv string=%s\n", string);
    sprintf(log, "putenv string=%s\n", string);
    write(my_fd, log, strlen(log));
    close(my_fd);

    return ret;
}

typedef unsigned int (*SLEEP) (unsigned int);

unsigned int sleep(unsigned int seconds) {
    char log[256];
    char return_data[256];
    unsigned int ret;

    int my_fd;
    my_fd = open("./log_profile", O_WRONLY | O_CREAT | O_APPEND);

    void *handle = NULL;
    SLEEP old_func = NULL;

    handle = dlopen("libc.so.6", RTLD_LAZY);
    old_func = (SLEEP) dlsym(handle, "sleep");
    
    ret = old_func(seconds);
    if (ret != 0) {
        printf("[NULL] ");
        sprintf(return_data, "[NULL] ");
        write(my_fd, return_data, strlen(return_data));

        printf("sleep seconds=%u\n", seconds);
        sprintf(log, "sleep seconds=%u\n", seconds);
        write(my_fd, log, strlen(log));
        close(my_fd);
        return ret;
    }

    // return data
    printf("[%u] ", ret);
    sprintf(return_data, "[%u] ", ret);
    write(my_fd, return_data, strlen(return_data));

    // function name and params
    printf("sleep seconds=%u\n", seconds);
    sprintf(log, "sleep seconds=%u\n", seconds);
    write(my_fd, log, strlen(log));
    close(my_fd);

    return ret;
}

typedef void* (*MMAP) (void*, size_t, int, int, int, off_t);

void* mmap(void* addr, size_t length, int prot, int flags, int fd, off_t offset) {
    char log[256];
    char return_data[256];
    void* ret;

    int my_fd;
    my_fd = open("./log_profile", O_WRONLY | O_CREAT | O_APPEND);

    void *handle = NULL;
    MMAP old_func = NULL;

    handle = dlopen("libc.so.6", RTLD_LAZY);
    old_func = (MMAP) dlsym(handle, "mmap");
    
    ret = old_func(addr,length,prot,flags,fd,offset);
    if (ret == NULL) {
        printf("[NULL] ");
        sprintf(return_data, "[NULL] ");
        write(my_fd, return_data, strlen(return_data));

        printf("mmap addr=%p,length=%ld,prot=%d,flags=%d,fd=%d,offset=%ld\n", addr, length, prot, flags, fd, offset);
        sprintf(log, "mmap addr=%p,length=%ld,prot=%d,flags=%d,fd=%d,offset=%ld\n", addr, length, prot, flags, fd, offset);
        write(my_fd, log, strlen(log));
        close(my_fd);
        return ret;
    }

    // return data
    printf("[%p] ", ret);
    sprintf(return_data, "[%p] ", ret);
    write(my_fd, return_data, strlen(return_data));

    // function name and params
    printf("mmap addr=%p,length=%ld,prot=%d,flags=%d,fd=%d,offset=%ld\n", addr, length, prot, flags, fd, offset);
    sprintf(log, "mmap addr=%p,length=%ld,prot=%d,flags=%d,fd=%d,offset=%ld\n", addr, length, prot, flags, fd, offset);
    write(my_fd, log, strlen(log));
    close(my_fd);

    return ret;
}

typedef int (*UNAME) (struct utsname*);

int uname(struct utsname* buf) {
    char log[256];
    char return_data[256];
    int ret;

    int my_fd;
    my_fd = open("./log_profile", O_WRONLY | O_CREAT | O_APPEND);

    void *handle = NULL;
    UNAME old_func = NULL;

    handle = dlopen("libc.so.6", RTLD_LAZY);
    old_func = (UNAME) dlsym(handle, "uname");
    
    ret = old_func(buf);
    if (ret != 0) {
        printf("[NULL] ");
        sprintf(return_data, "[NULL] ");
        write(my_fd, return_data, strlen(return_data));

        printf("uname sysname=%s,nodename=%s,release=%s,version=%s,machine=%s\n", buf -> sysname, buf -> nodename, buf -> release, buf -> version, buf -> machine);
        sprintf(log, "uname sysname=%s,nodename=%s,release=%s,version=%s,machine=%s\n", buf -> sysname, buf -> nodename, buf -> release, buf -> version, buf -> machine);
        write(my_fd, log, strlen(log));
        close(my_fd);
        return ret;
    }

    // return data
    printf("[%d] ", ret);
    sprintf(return_data, "[%d] ", ret);
    write(my_fd, return_data, strlen(return_data));

    // function name and params
    printf("uname sysname=%s,nodename=%s,release=%s,version=%s,machine=%s\n", buf -> sysname, buf -> nodename, buf -> release, buf -> version, buf -> machine);
    sprintf(log, "uname sysname=%s,nodename=%s,release=%s,version=%s,machine=%s\n", buf -> sysname, buf -> nodename, buf -> release, buf -> version, buf -> machine);
    write(my_fd, log, strlen(log));
    close(my_fd);

    return ret;
}

typedef time_t (*TIME) (time_t*);

time_t time(time_t* t) {
    char log[256];
    char return_data[256];
    time_t ret;

    int my_fd;
    my_fd = open("./log_profile", O_WRONLY | O_CREAT | O_APPEND);

    void *handle = NULL;
    TIME old_func = NULL;

    handle = dlopen("libc.so.6", RTLD_LAZY);
    old_func = (TIME) dlsym(handle, "time");
    
    ret = old_func(t);
    if (ret != 0) {
        printf("[NULL] ");
        sprintf(return_data, "[NULL] ");
        write(my_fd, return_data, strlen(return_data));

        printf("time t=%ld\n", t);
        sprintf(log, "time t=%ld\n", t);
        write(my_fd, log, strlen(log));
        close(my_fd);
        return ret;
    }

    // return data
    printf("[%ld] ", ret);
    sprintf(return_data, "[%ld] ", ret);
    write(my_fd, return_data, strlen(return_data));

    // function name and params
    printf("time t=%ld\n", t);
    sprintf(log, "time t=%ld\n", t);
    write(my_fd, log, strlen(log));
    close(my_fd);

    return ret;
}

typedef char* (*CTIME) (const time_t*);

char* ctime(const time_t* timep) {
    char log[256];
    char return_data[256];
    char* ret;

    int my_fd;
    my_fd = open("./log_profile", O_WRONLY | O_CREAT | O_APPEND);

    void *handle = NULL;
    CTIME old_func = NULL;

    handle = dlopen("libc.so.6", RTLD_LAZY);
    old_func = (CTIME) dlsym(handle, "ctime");
    
    ret = old_func(timep);
    if (ret == NULL) {
        printf("[NULL] ");
        sprintf(return_data, "[NULL] ");
        write(my_fd, return_data, strlen(return_data));

        printf("ctime timep=%p\n", timep);
        sprintf(log, "ctime timep=%p\n", timep);
        write(my_fd, log, strlen(log));
        close(my_fd);
        return ret;
    }

    // return data
    printf("[%s] ", ret);
    sprintf(return_data, "[%s] ", ret);
    write(my_fd, return_data, strlen(return_data));

    // function name and params
    printf("ctime timep=%p\n", timep);
    sprintf(log, "ctime timep=%p\n", timep);
    write(my_fd, log, strlen(log));
    close(my_fd);

    return ret;
}

typedef int (*NANOSLEEP) (const struct timespec*, struct timespec*);

int nanosleep(const struct timespec* req, struct timespec* rem) {
    char log[256];
    char return_data[256];
    int ret;

    int my_fd;
    my_fd = open("./log_profile", O_WRONLY | O_CREAT | O_APPEND);

    void *handle = NULL;
    NANOSLEEP old_func = NULL;

    handle = dlopen("libc.so.6", RTLD_LAZY);
    old_func = (NANOSLEEP) dlsym(handle, "nanosleep");
    
    ret = old_func(req,rem);
    if (ret != 0) {
        printf("[NULL] ");
        sprintf(return_data, "[NULL] ");
        write(my_fd, return_data, strlen(return_data));

        printf("nanosleep tv_sec=%ld,tv_nsec=%ld\n", req -> tv_sec, req -> tv_nsec);
        sprintf(log, "nanosleep tv_sec=%ld,tv_nsec=%ld\n", req -> tv_sec, req -> tv_nsec);
        write(my_fd, log, strlen(log));
        close(my_fd);
        return ret;
    }

    // return data
    printf("[%d] ", ret);
    sprintf(return_data, "[%d] ", ret);
    write(my_fd, return_data, strlen(return_data));

    // function name and params
    printf("nanosleep tv_sec=%ld,tv_nsec=%ld\n", req -> tv_sec, req -> tv_nsec);
    sprintf(log, "nanosleep tv_sec=%ld,tv_nsec=%ld\n", req -> tv_sec, req -> tv_nsec);
    write(my_fd, log, strlen(log));
    close(my_fd);

    return ret;
}

